# Generated by Django 5.0.1 on 2024-02-11 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user_likes',
            new_name='users_likes',
        ),
    ]
